// <auto-generated />
using System;
using Kognito.Tarefas.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kognito.Tarefas.Infra.Migrations
{
    [DbContext(typeof(TarefasContext))]
    [Migration("20241129143249_altera campo de titulo para id")]
    partial class alteracampodetituloparaid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kognito.Tarefas.Domain.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Atrasada")
                        .HasColumnType("bit");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntregueEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Entregas", (string)null);
                });

            modelBuilder.Entity("Kognito.Tarefas.Domain.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntregaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ValorNota")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId");

                    b.ToTable("Notas", (string)null);
                });

            modelBuilder.Entity("Kognito.Tarefas.Domain.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFinalEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("Kognito.Tarefas.Domain.Entrega", b =>
                {
                    b.HasOne("Kognito.Tarefas.Domain.Tarefa", "Tarefa")
                        .WithMany("Entregas")
                        .HasForeignKey("TarefaId")
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Kognito.Tarefas.Domain.Nota", b =>
                {
                    b.HasOne("Kognito.Tarefas.Domain.Entrega", "Entrega")
                        .WithMany("Notas")
                        .HasForeignKey("EntregaId")
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("Kognito.Tarefas.Domain.Entrega", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Kognito.Tarefas.Domain.Tarefa", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
